### ISSUE TITLE
Error When Running workflow.py Due to Incorrect OpenAI API Usage

### ISSUE THREAD

**Issue by zimingyou01** [KevinCL16/MatPlotAgent#3]
Hi, I really appreciate your work for data science agent and its evaluation.

**Description:**
While following the installation steps in the README and running workflow.py, I encountered an error:
```
Traceback (most recent call last):
  File "/data1/yzm/MatPlotAgent/test.py", line 13, in <module>
    response = openai.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yzm/miniconda3/envs/matplotbench/lib/python3.11/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yzm/miniconda3/envs/matplotbench/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 859, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/yzm/miniconda3/envs/matplotbench/lib/python3.11/site-packages/openai/_base_client.py", line 1280, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yzm/miniconda3/envs/matplotbench/lib/python3.11/site-packages/openai/_base_client.py", line 957, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/yzm/miniconda3/envs/matplotbench/lib/python3.11/site-packages/openai/_base_client.py", line 1061, in _request
    raise self._make_status_error_from_response(err.response) from None
**openai.NotFoundError: 404 page not found**
```
**Cause:**
I believe the issue stems from incorrect API call usage and outdated endpoint configurations.
To be specific, the following code block triggers errors:
```python
openai.chat.completions.create(...)
```
**Proposed Solution:**
And I find the issue will be fixed after replacing the code block with:
```python
# modify the code to create a client instance before making the API call 
client = openai.OpenAI(
        api_key=API_KEY,
        base_url=BASE_URL,
    )

response = client.chat.completions.create(
    model=model_type, messages=messages, temperature=temperature, max_tokens=1000
)
```
I hope this helps clarify the issue. Making this adjustment would prevent similar problems for new developers and improve the overall experience. Thank you for your hard work!

**Comment by KevinCL16** [comment]
Thank you very much for bringing up this issue. Hope you can have fun with our work.
